using System.ComponentModel.DataAnnotations.Schema;
using ConectOne.Domain.Entities;

namespace ShoppingModule.Domain.Entities
{
    /// <summary>
    /// Represents an invoice issued to a customer, containing details about the associated sales order, customer
    /// information, and line items.
    /// </summary>
    /// <remarks>The <see cref="Invoice"/> class includes properties for identifying the invoice, linking it
    /// to a customer and a sales order, and managing a collection of detailed line items. Each invoice is uniquely
    /// identified by its <see cref="InvoiceNr"/>.</remarks>
    public class Invoice : EntityBase<string>
    {
        /// <summary>
        /// Gets or sets the unique invoice number generated by the database.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int InvoiceNr { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the customer.
        /// </summary>
        public string CustomerId { get; set; }

        /// <summary>
        /// Gets or sets the sales order associated with the current operation.
        /// </summary>
        public SalesOrder SalesOrder { get; set;}

        #region Collections

        /// <summary>
        /// Gets or sets the collection of invoice details associated with the invoice.
        /// </summary>
        public ICollection<InvoiceDetail> Details { get; set; } = new List<InvoiceDetail>();

        #endregion
    }
}
