using ProductsModule.Domain.DataTransferObjects;

namespace ProductsModule.Application.ViewModels;

/// <summary>
/// Represents a product metadata view model that contains detailed information about a product's metadata.
/// This view model is used to transfer metadata information between application layers.
/// </summary>
public class ProductMetadataViewModel
{
    #region Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="ProductMetadataViewModel"/> class.
    /// This constructor initializes the object with default values.
    /// </summary>
    public ProductMetadataViewModel() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="ProductMetadataViewModel"/> class using data from a <see cref="ProductMetadataDto"/>.
    /// This constructor maps the data transfer object properties onto the view model.
    /// </summary>
    /// <param name="dto">The data transfer object containing the product metadata details.</param>
    public ProductMetadataViewModel(ProductMetadataDto dto)
    {
        Id = dto.Id;
        Name = dto.Name;
        Value = dto.Value;
        ProductId = dto.ProductId;
    }

    #endregion

    #region Constructors

    /// <summary>
    /// Gets or sets the unique identifier of the product metadata.
    /// A new GUID string is generated by default to uniquely identify each instance.
    /// </summary>
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// Gets or sets the name of the product metadata.
    /// This field is required and represents the key or title of the metadata attribute.
    /// </summary>
    public string Name { get; set; } = null!;

    /// <summary>
    /// Gets or sets the value associated with the product metadata.
    /// This field is optional and holds the corresponding data for the metadata attribute.
    /// </summary>
    public string? Value { get; set; }

    /// <summary>
    /// Gets or sets the unique identifier of the associated product.
    /// This field should be provided when linking the metadata to its corresponding product.
    /// </summary>
    public string? ProductId { get; set; }

    #endregion

    #region Methods

    /// <summary>
    /// Converts the current instance of <see cref="ProductMetadata"/> to a <see cref="ProductMetadataDto"/>.
    /// </summary>
    /// <returns>A <see cref="ProductMetadataDto"/> object containing the data from the current instance.</returns>
    public ProductMetadataDto ToDto()
    {
        return new ProductMetadataDto()
        {
            Id = Id,
            Name = Name,
            Value = Value,
            ProductId = ProductId
        };
    }

    #endregion
}
